### ISSUE TITLE
No license included in package metadata

### ISSUE THREAD

**Issue by thejcannon** [python-lsp/python-lsp-jsonrpc#18]
:wave: I see that the project uses the MIT License, but the uploaded `sdist` and `wheel` don't include that in the Trove Classifiers or package metadata.

**Comment by ccordoba12** [comment]
Hey @thejcannon, thanks for reporting. You're welcome to submit a pull request to fix that.

**Comment by thejcannon** [comment]
I think the change has already been made: https://github.com/python-lsp/python-lsp-jsonrpc/blob/c73fbdba2eeb99b7b145dcda76e62250552feda4/pyproject.toml#L12 you just need to publish a new version :smile:

**Comment by thejcannon** [comment]
Although it doesn't have the trove classifier. Let me add that
